from typing import List

def unsafe_hs_{{cookiecutter.__project_slug_snakecase}}_version() -> str: ...
def unsafe_hs_{{cookiecutter.__project_slug_snakecase}}_main() -> None: ...
def unsafe_hs_init(args: List[str]) -> None: ...
def unsafe_hs_exit() -> None: ...
